repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: .(in|out)$
  - id: check-yaml
    args: [--unsafe]
  - id: end-of-file-fixer
- repo: https://github.com/finsberg/clang-format-docs
  rev: v0.3.0
  hooks:
  - id: clang-format-docs
    additional_dependencies: [clang-format==19.1.6]
    args: [--style=file:.clang-format]
    files: ^docs/
    types: [markdown]
    # Ignorujemy lekcje A2, A3 i A8, w których specjalnie są błędy.
    exclude: ^docs/A-podstawy-programowania/A[238]
